### ISSUE TITLE
Update submarine HVDC cable cost

### ISSUE THREAD

**Issue by p-glaum** [PyPSA/technology-data#93]
we should maybe update the HVDC submarine cable because the current 471.16 €/MWkm are half the cost of other sources like Härtel 2017 with 960 €/MWkm or 1187€/MWkm from ETYS15

**Comment by p-glaum** [comment]
I will investigate a bit further and as soon as I am certain, I create a PR

**Comment by fvdborre** [comment]
$The cumulative new capacity of VSC HVDC grows exponentially. See: https://www.hitachi.com/rev/archive/2020/r2020_04/pdf/gir.pdf 

Furthermore, HVDC components have a very high learning rate:
Learning rate cable: 32%
Learning rate converter station: 29%
https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=fa4b0f213124ec031f1f8805807f7610b15dc4c5 

More about HVDC costs, see: https://blog.sintef.com/sintefenergy/future-hvdc-grids-yes-please-but-what-is-the-price-tag/

**Comment by fneum** [comment]
closed via https://github.com/PyPSA/technology-data/commit/b29f72900af6d3a79ec05b15dcbb40e6cc80659d

**Comment by fvdborre** [comment]
Hi, 

I just found out that there is a new publication about the cost model of HVDC. It could be helpful for offshore grid planning since it makes a distinction between onshore and offshore nodes. I'm not sure if this complexity is allowed within PyPSA.

https://sintef.brage.unit.no/sintef-xmlui/bitstream/handle/11250/3077586/Vrana2023iic_AAM.pdf?sequence=1
